'use strict';
const S=window.SAE,N=S.n,Dd=S.dict,C={},U=S.num.usuarios,LA=S.num.latitud,LO=S.num.longitud,$=s=>document.querySelector(s);
document.head.insertAdjacentHTML('beforeend','<style>#fmap{height:420px;border-radius:12px;border:1px solid var(--line);z-index:0}.tl td,.tl th{text-align:left}.lbl{font:600 11px Inter,sans-serif;padding:2px 6px;border-radius:6px}.acts{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}tr[data-f]:hover td{background:rgba(245,158,11,.18)}</style>');
const rev={};[...S.A].forEach((ch,k)=>rev[ch]=k);
for(const c in S.str){const s=S.str[c],a=new Uint8Array(N);for(let i=0;i<N;i++)a[i]=rev[s[i]];C[c]=a}
for(const c in S.int)C[c]=Uint32Array.from(S.int[c]);
const v=(c,i)=>Dd[c][C[c][i]],fmt=n=>Math.round(n).toLocaleString('es-PE'),f1=n=>n.toLocaleString('es-PE',{maximumFractionDigits:1,minimumFractionDigits:1}),pc=(a,b)=>b?f1(100*a/b)+'%':'—',lb=s=>s||'Sin dato';
const FIL=[['periodo_sae','Periodo'],['grupo_sae_educunas','Grupo SAE / Educunas'],['unidad_territorial','Unidad territorial'],['departamento','Departamento'],['provincia','Provincia'],['distrito','Distrito'],['area','Área'],['nivel','Nivel educativo'],['modalidad','Modalidad'],['tipo_racion','Tipo de ración']];
const sel={};FIL.forEach(([c])=>sel[c]=-1);sel.periodo_sae=Dd.periodo_sae.indexOf('2027');
const TT={res:'Resumen ejecutivo',ut:'Unidades territoriales',mod:'Modalidad y forma',inf:'Infraestructura (Ficha 2025)',his:'Comparación histórica 2026–2027',grp:'Items de SSEE',fic:'Fichas por SSEE',tab:'Resumen en tablas',am:'Ayuda memoria',edu:'EDUCUNAS 2026 · Seguimiento'};
let tab='res',R=[],cache={k:'',v:null},MAT='co';
const hasF=i=>v('iieeconfichadeinfra2no25',i)==='Si';
function ix(skipPer,per){const k=JSON.stringify(sel)+skipPer+per;if(cache.k===k)return cache.v;const a=[],act=FIL.filter(([c])=>sel[c]>=0&&!(skipPer&&c==='periodo_sae')).map(([c])=>[C[c],sel[c]]);if(per!=null)act.push([C.periodo_sae,per]);
 for(let i=0;i<N;i++){let ok=1;for(const[x,s]of act)if(x[i]!==s){ok=0;break}if(ok)a.push(i)}cache={k,v:a};return a}
function cnt(ix,c,asc){const n=Dd[c].length,a=new Float64Array(n),u=new Float64Array(n),x=C[c];for(const i of ix){a[x[i]]++;u[x[i]]+=U[i]}
 const r=Dd[c].map((l,k)=>[lb(l),a[k],u[k]]).filter(r=>r[1]);return asc?r.sort((p,q)=>p[0]<q[0]?-1:1):r.sort((p,q)=>q[1]-p[1])}
const dat=(t,h,r,n)=>R.push({t,h,r,n});
function bars(t,rows,tot,lim){rows=lim?rows.slice(0,lim):rows;const mx=Math.max(...rows.map(r=>r[1]),1);dat(t,['Categoría','SSEE','%','Usuarios'],rows.map(r=>[r[0],r[1],pc(r[1],tot),r[2]??'']));
 return`<div class=card><h3>${t}</h3>${rows.map(r=>`<div class=b><span>${r[0]}</span><div><i style="width:${100*r[1]/mx}%"></i></div><b>${fmt(r[1])} · ${pc(r[1],tot)}</b></div>`).join('')}</div>`}
function stack(t,labs,cols,cs,sub='Información 2025'){const tot=cs.reduce((a,b)=>a+b,0);dat(t,['Categoría','SSEE','%'],labs.map((l,k)=>[l,cs[k],pc(cs[k],tot)]));
 return`<div class=card><h3>${t}<small>${sub}</small></h3><div class=stk>${cs.map((c,k)=>`<i style="width:${100*c/(tot||1)}%;background:${cols[k]}"></i>`).join('')}</div><div class=lg>${labs.map((l,k)=>`<span><em style="background:${cols[k]}"></em>${l}: <b>${fmt(cs[k])}</b> (${pc(cs[k],tot)})</span>`).join('')}</div></div>`}
function tbl(t,h,rows,keys,lim=400,o={}){dat(t,h,rows);const vis=rows.slice(0,lim);return`<div class=card><h3>${t}<small>${rows.length>lim?`mostrando ${lim} de ${fmt(rows.length)} · el reporte incluye todo`:''}</small></h3><div class=${o.ns?'"tw ns"':'tw'}><table${o.c?' class='+o.c:''}><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${vis.map((r,j)=>`<tr ${keys&&keys[j]!=null?`data-k="${keys[j]}"`:''}${o.tot&&j===rows.length-1?' class=tt':''}>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
const kpis=(a,tt='Indicadores clave')=>{dat(tt,['Indicador','Valor','Detalle'],a.map(k=>[k[0],k[1],k[2]]));return`<div class=kpis>${a.map(k=>`<div class=kpi><small>${k[0]}</small><strong>${k[1]}</strong><span>${k[2]}</span></div>`).join('')}</div>`};
const KIT=['Brecha: no recibió / no posee','Brecha: kit en mal estado','Sin brecha: óptimo o aceptable'],KC=['#e11d48','#f59e0b','#059669'],AMB=['No tiene ambiente','Ambiente exclusivo','Ambiente compartido'],AC=['#e11d48','#059669','#2563eb'];
const code3=(ix,c)=>{const a=[0,0,0];for(const i of ix){const x=v(c,i);if(x==='0'||x==='1'||x==='2')a[+x]++}return a};
const opt=i=>['Si','1'].includes(v('cocina_optima',i));
/* ---------- pestañas ---------- */
const T={};
T.res=ix=>{const n=ix.length,u=ix.reduce((a,i)=>a+U[i],0),rur=ix.filter(i=>v('area',i)==='Rural').length;
 return kpis([['Servicios (SSEE)',fmt(n),'Servicios educativos atendidos'],['Usuarios',fmt(u),'Prom. '+f1(u/(n||1))+' por SSEE'],['Ámbito rural',pc(rur,n),fmt(rur)+' SSEE']])
 +`<div class=grid2>`+bars('Por modalidad',cnt(ix,'modalidad'),n)+bars('Por nivel educativo',cnt(ix,'nivel'),n)+`</div>`
 +mcard(mt('Modalidades y formas de atención','Modalidad / forma de atención',ix,mdl,null,norF))
 +`<div class=grid2>`+bars('SSEE, por rango de usuarios',rngRows(ix),n)+bars('SSEE, por unidad territorial (Top 12)',cnt(ix,'unidad_territorial'),n,12)+`</div>`
 +bars('SSEE, por tipo de ración',cntK(ix,rac),n)+cobCards()};
T.ut=ix=>{const c='unidad_territorial',k=Dd[c].length,z=()=>new Float64Array(k),A={n:z(),u:z(),r:z(),f:z(),m:z(),c:z(),b:z(),o:z()};
 for(const i of ix){const g=C[c][i];A.n[g]++;A.u[g]+=U[i];if(v('area',i)==='Rural')A.r[g]++;if(hasF(i)){A.f[g]++;if(v('kitmenaje',i)!=='2')A.m[g]++;if(v('kitcocina',i)!=='2')A.c[g]++;if(v('kitmobiliario',i)!=='2')A.b[g]++;if(opt(i))A.o[g]++}}
 const o=[...Dd[c].keys()].filter(g=>A.n[g]).sort((a,b)=>A.u[b]-A.u[a]),S=a=>o.reduce((s,g)=>s+a[g],0),terr=['unidad_territorial','departamento','provincia','distrito'].some(x=>sel[x]>=0),
 row=(l,n,u,r,f,m,cc,b,op)=>[l,fmt(n),fmt(u),pc(r,n),pc(f,n),pc(m,f),pc(cc,f),pc(b,f),pc(op,f)],
 rows=o.map(g=>row(Dd[c][g],A.n[g],A.u[g],A.r[g],A.f[g],A.m[g],A.c[g],A.b[g],A.o[g]));
 rows.push(row(terr?'Total (según filtros)':'Total nacional',S(A.n),S(A.u),S(A.r),S(A.f),S(A.m),S(A.c),S(A.b),S(A.o)));
 return`<div class=note>Clic en una fila para filtrar toda la página por esa unidad territorial. Brechas e indicadores de cocina calculados sobre SSEE con ficha 2025.</div>`+tbl('Resumen por unidad territorial',['Unidad territorial','SSEE','Usuarios','% rural','% con ficha 2025','% brecha menaje','% brecha cocina','% brecha mobiliario','% cocina óptima'],rows,o.map(g=>'ut:'+g),rows.length,{ns:1,tot:1})};
T.mod=ix=>{const n=ix.length,u=ix.reduce((a,i)=>a+U[i],0),ka=cntK(ix,mdl);
 return`<div class=card><h3>Filtro de modalidad<small>se aplica a toda la página</small></h3><div class=seg>${[[-1,'Todas'],...Dd.modalidad.map((m,k)=>[k,tcase(m)])].map(([k,l])=>`<button data-mod=${k} class="${sel.modalidad===k?'on':''}">${l}</button>`).join('')}</div></div>`
 +kpis(ka.map(r=>[tcase(r[0]),fmt(r[1])+' SSEE',fmt(r[2])+' usuarios · '+pc(r[2],u)]))+`<div class=grid2>`+bars('Modalidad',ka,n)+bars('Forma de atención',cntK(ix,norF),n)+bars('Tipo de ración',cntK(ix,rac),n)+bars('Grupo SAE / Educunas',cnt(ix,'grupo_sae_educunas'),n)+`</div>`};
const MC={piso:{al:'material_predominante_piso_almac',co:'material_predominante_piso_cocin',cm:'material_predominante_piso_comed'},pared:{al:'material_predominante_paredes_al',co:'material_predominante_paredes_co',cm:'material_predominante_pared_com'},techo:{al:'material_predominante_techo_alma',co:'material_predominante_techo_coci',cm:'material_predominante_techo_come'}};
T.inf=ix=>{const fi=ix.filter(hasF),n=ix.length,sn=n-fi.length,m=code3(fi,'kitmenaje');let h=kpis([['Con ficha de infraestructura 2025',pc(fi.length,n),fmt(fi.length)+' de '+fmt(n)+' SSEE'],['Brecha en kit de menaje',pc(m[0]+m[1],fi.length),'Sobre SSEE con ficha 2025'],['Cocina en condición óptima',pc(fi.filter(opt).length,fi.length),'Sobre SSEE con ficha 2025']])
 +`<div class=note>🗓 <b>Información de la Ficha de Infraestructura 2025.</b> ${fmt(fi.length)} de ${fmt(n)} SSEE (${pc(fi.length,n)}) cuentan con ficha; ${fmt(sn)} no tienen ficha 2025 y por eso no registran datos de estado de infraestructura.</div>`;
 h+=`<div class=grid2>`+stack('Kit de menaje',KIT,KC,code3(fi,'kitmenaje'))+stack('Kit de cocina',KIT,KC,code3(fi,'kitcocina'))+stack('Kit de mobiliario',KIT,KC,code3(fi,'kitmobiliario'))+`</div><div class=grid2>`+stack('Ambiente de cocina',AMB,AC,code3(fi,'ambientecocina'))+stack('Ambiente de almacén',AMB,AC,code3(fi,'ambientealmacen'))+stack('Ambiente de comedor',AMB,AC,code3(fi,'ambientecomedor'))+`</div>`;
 const fN=fi.length;h+=`<div class=grid2>`+bars('Ficha de infraestructura 2025',cnt(ix,'iieeconfichadeinfra2no25'),n)+bars('Abastecimiento de agua · 2025',cnt(fi,'abastecimiento_agua_por'),fN)+bars('Servicio higiénico conectado a · 2025',cnt(fi,'servicio_higienico_conectado_a'),fN)+bars('Alumbrado proviene de · 2025',cnt(fi,'alumbrado_proviene_de'),fN)+`</div>`;
 h+=`<div class=card><h3>Material predominante · 2025</h3><div class=seg>${[['co','Cocina'],['al','Almacén'],['cm','Comedor']].map(([k,l])=>`<button data-mat=${k} class="${MAT===k?'on':''}">${l}</button>`).join('')}</div><div class=grid2>`+['piso','pared','techo'].map(m=>bars('Material del '+m,cnt(fi,MC[m][MAT]),fN).replace('class=card','class=nocard')).join('')+`</div></div>`;return h+anCocinas()};
T.his=()=>{const ps=Dd.periodo_sae,ixa=ix(1),c='unidad_territorial',m=ps.map(()=>new Map()),tot=ps.map(()=>[0,0]),keys=ps.map(()=>new Set());
 for(const i of ixa){const p=C.periodo_sae[i],g=C[c][i];let o=m[p].get(g);if(!o)m[p].set(g,o=[0,0]);o[0]++;o[1]+=U[i];tot[p][0]++;tot[p][1]+=U[i];keys[p].add(C.cod_modular[i]*128+C.anexo[i])}
 const gs=[...new Set(m.flatMap(x=>[...x.keys()]))].sort((a,b)=>(m[2].get(b)||[0,0])[1]-(m[2].get(a)||[0,0])[1]),L=ps.length-1,d=(a,b)=>(a-b>0?'+':'')+fmt(a-b);
 const gl=(p,g)=>(m[p].get(g)||[0,0]);
 const rows=gs.map(g=>[Dd[c][g],...ps.map((_,p)=>fmt(gl(p,g)[0])),d(gl(L,g)[0],gl(L-1,g)[0]),...ps.map((_,p)=>fmt(gl(p,g)[1])),d(gl(L,g)[1],gl(L-1,g)[1])]);
 rows.push(['TOTAL',...tot.map(t=>fmt(t[0])),d(tot[L][0],tot[L-1][0]),...tot.map(t=>fmt(t[1])),d(tot[L][1],tot[L-1][1])]);
 let nw=0,sa=0,co=0;keys[L].forEach(k=>keys[L-1].has(k)?co++:nw++);keys[L-1].forEach(k=>keys[L].has(k)||sa++);
 return`<div class=note>Esta vista ignora el filtro de periodo y compara los tres periodos con los demás filtros aplicados.</div>`+kpis([...ps.map((p,k)=>['SSEE '+p,fmt(tot[k][0]),fmt(tot[k][1])+' usuarios']),['Nuevos en '+ps[L],fmt(nw),'No estaban en '+ps[L-1]],['Salen en '+ps[L],fmt(sa),'Estaban en '+ps[L-1]],['Continúan',fmt(co),'En ambos periodos']])
 +tbl('Evolución por unidad territorial',['Unidad territorial',...ps.map(p=>'SSEE '+p),'Δ SSEE',...ps.map(p=>'Usuarios '+p),'Δ Usuarios'],rows)};
/* ---------- geometría ---------- */
function geo(pts,type){if(!pts.length)return{poly:[],a:0,p:0};const la0=pts.reduce((a,p)=>a+p[0],0)/pts.length,lo0=pts.reduce((a,p)=>a+p[1],0)/pts.length,kx=111.32*Math.cos(la0*Math.PI/180),ky=110.574;
 const xy=pts.map(p=>[(p[1]-lo0)*kx,(p[0]-la0)*ky]),back=q=>[q[1]/ky+la0,q[0]/kx+lo0],cr=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]);
 const s=[...new Map(xy.map(p=>[p[0]+','+p[1],p])).values()].sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let h=s;
 if(s.length>2){const lo=[],up=[];for(const p of s){while(lo.length>1&&cr(lo[lo.length-2],lo[lo.length-1],p)<=0)lo.pop();lo.push(p)}for(const p of[...s].reverse()){while(up.length>1&&cr(up[up.length-2],up[up.length-1],p)<=0)up.pop();up.push(p)}h=lo.slice(0,-1).concat(up.slice(0,-1))}
 const ar=P=>Math.abs(P.reduce((a,p,k)=>{const q=P[(k+1)%P.length];return a+p[0]*q[1]-q[0]*p[1]},0))/2,pe=P=>P.reduce((a,p,k)=>{const q=P[(k+1)%P.length];return a+Math.hypot(p[0]-q[0],p[1]-q[1])},0);let P=h;
 const bb=(Q,t=0)=>{let x0=1e9,x1=-1e9,y0=1e9,y1=-1e9;for(const q of Q){x0=Math.min(x0,q[0]);x1=Math.max(x1,q[0]);y0=Math.min(y0,q[1]);y1=Math.max(y1,q[1])}return[x0,y0,x1,y1]};
 if(type==='env'){const[a,b,c,d]=bb(h);P=[[a,b],[c,b],[c,d],[a,d]]}
 else if(type==='rect'&&h.length>2){let best=1e18;for(let k=0;k<h.length;k++){const p=h[k],q=h[(k+1)%h.length],t=Math.atan2(q[1]-p[1],q[0]-p[0]),co=Math.cos(t),si=Math.sin(t),R=h.map(z=>[z[0]*co+z[1]*si,-z[0]*si+z[1]*co]),[a,b,c,d]=bb(R),A=(c-a)*(d-b);if(A<best){best=A;P=[[a,b],[c,b],[c,d],[a,d]].map(z=>[z[0]*co-z[1]*si,z[0]*si+z[1]*co])}}}
 else if(type==='circ'){let c=h[0].slice(),r=0;for(let k=1;k<200;k++){let f=h[0],md=0;for(const z of h){const dd=Math.hypot(z[0]-c[0],z[1]-c[1]);if(dd>md){md=dd;f=z}}c=[c[0]+(f[0]-c[0])/(k+1),c[1]+(f[1]-c[1])/(k+1)]}for(const z of h)r=Math.max(r,Math.hypot(z[0]-c[0],z[1]-c[1]));P=Array.from({length:72},(_,k)=>[c[0]+r*Math.cos(k*Math.PI/36),c[1]+r*Math.sin(k*Math.PI/36)])}
 return{poly:P.map(back),a:P.length>2?ar(P):0,p:P.length>1?pe(P):0}}
const G={by:'item',geo:'hull',sel:null,list:[],ixs:[],q:''};let map,lay,BASE='OpenStreetMap (estándar)';
const GB={item:'Item (único por UT)',comite:'Comité de gestión',distrito:'Distrito',all:'Todos juntos'},GG={hull:'Envolvente convexa (Convex hull)',env:'Envolvente rectangular (Envelope)',rect:'Rectángulo de menor área',circ:'Círculo mínimo (Circle)'};
T.grp=ix=>{if(map){map.remove();map=null}const m=new Map();for(const i of ix){const k=gk(i);let o=m.get(k);if(!o)m.set(k,o={i0:i,n:0,u:0,pts:[]});o.n++;o.u+=U[i];if(LA[i]<-0.5&&LA[i]>-19&&LO[i]<-68&&LO[i]>-82)o.pts.push([LA[i],LO[i]])}
 G.list=[...m.entries()].map(([k,o])=>{const g=geo(o.pts,G.geo),i=o.i0;return{k,o,g,label:G.by==='all'?'Todos los SSEE filtrados':G.by==='distrito'?v('distrito',i)+' · '+v('provincia',i):v(G.by,i)+' · '+v('unidad_territorial',i)}}).sort((a,b)=>b.o.u-a.o.u);
 if(!G.sel||!G.list.find(x=>x.k==G.sel))G.sel=G.list[0]?.k;
 const rows=G.list.map(x=>[x.label,fmt(x.o.n),fmt(x.o.u),f1(x.g.a),f1(x.g.p)]);
 return`<div class=card><h3>Mapa de servicios educativos · Minimum Bounding Geometry</h3><div class=ctl><label>Agrupar por<select id=gby>${Object.entries(GB).map(([k,l])=>`<option value=${k} ${G.by===k?'selected':''}>${l}</option>`).join('')}</select></label><label>Geometría envolvente<select id=ggeo>${Object.entries(GG).map(([k,l])=>`<option value=${k} ${G.geo===k?'selected':''}>${l}</option>`).join('')}</select></label></div><div id=gsel></div><div id=map></div></div>`
 +tbl('Grupo · SSEE · Usuarios · Área (km²) · Perímetro (km)',['Grupo','SSEE','Usuarios','Área (km²)','Perímetro (km)'],rows,G.list.map(x=>'g:'+x.k),5000).replace('<div class=tw>','<input id=gq class=sq value="'+G.q+'" placeholder="🔍 Buscar grupo (ej. LIMA 3, PIURA 2, un distrito…)" autocomplete=off><div class=tw>')};
const gfilter=()=>{const q=G.q.trim().toLowerCase();document.querySelectorAll('tr[data-k^="g:"]').forEach(r=>r.hidden=!!q&&!r.textContent.toLowerCase().includes(q))};
function newMap(id){const at='© OpenStreetMap',ct='© OpenStreetMap © CARTO',B={'OpenStreetMap (estándar)':L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:at}),'OpenStreetMap Humanitario':L.tileLayer('https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',{maxZoom:19,attribution:at+' · HOT'}),'Topográfico (OpenTopoMap)':L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:at+' · OpenTopoMap'}),'Claro (CARTO + OSM)':L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:19,attribution:ct}),'Oscuro (CARTO + OSM)':L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:19,attribution:ct})};
 const m=L.map(id,{preferCanvas:true,layers:[B[BASE]||B['OpenStreetMap (estándar)']]});L.control.layers(B,null,{collapsed:false}).addTo(m);L.control.scale({imperial:false}).addTo(m);m.on('baselayerchange',e=>BASE=e.name);const l=L.layerGroup().addTo(m);
 const lg=L.control({position:'bottomleft'});lg.onAdd=()=>{const d=L.DomUtil.create('div');d.style.cssText='background:#fff;color:#0f172a;padding:6px 10px;border-radius:8px;font:600 11px Inter,sans-serif;box-shadow:0 1px 6px rgba(0,0,0,.3)';d.innerHTML='<span style="color:#059669">●</span> Con ficha 2025 &nbsp; <span style="color:#e11d48">●</span> Sin ficha 2025 &nbsp; <span style="color:#1d4ed8">▭</span> Envolvente';return d};lg.addTo(m);return{m,l}}
function drawMap(){const x=G.list.find(z=>z.k==G.sel);if(!x)return;$('#gsel').innerHTML=`<div class=kpis style="margin-bottom:12px"><div class=kpi><small>Grupo</small><strong style="font-size:1.05rem">${x.label}</strong></div><div class=kpi><small>SSEE</small><strong>${fmt(x.o.n)}</strong></div><div class=kpi><small>Usuarios</small><strong>${fmt(x.o.u)}</strong></div><div class=kpi><small>Área (km²)</small><strong>${f1(x.g.a)}</strong></div><div class=kpi><small>Perímetro (km)</small><strong>${f1(x.g.p)}</strong></div></div>`;
 document.querySelectorAll('tr[data-k]').forEach(r=>r.classList.toggle('sel',r.dataset.k==='g:'+G.sel));
 if(!window.L)return setTimeout(drawMap,300);if(!map){const o=newMap('map');map=o.m;lay=o.l;ghl=L.layerGroup().addTo(map);map.on('moveend zoomend',()=>lbls(map,lay))}
 lay.clearLayers();ghl.clearLayers();const pts=[];for(const i of ix(0))if(sameGrp(i,x.k)&&LA[i]<-0.5)pts.push(i);pts.slice(0,9000).forEach(i=>{const k=L.circleMarker([LA[i],LO[i]],{radius:6,color:hasF(i)?'#059669':'#e11d48',weight:1.5,fillOpacity:.8});k._nm=v('nombre_ie',i)+' · '+v('nivel',i)+' · '+fmt(U[i])+' usuarios';k.on('click',()=>{ficha(i);focusF(i)}).on('mouseover',()=>k.setStyle({radius:9,weight:3})).on('mouseout',()=>k.setStyle({radius:6,weight:1.5})).addTo(lay)});
 if(x.g.poly.length>2){const p=L.polygon(x.g.poly,{color:'#1d4ed8',weight:2,fillOpacity:.08}).addTo(lay);map.fitBounds(p.getBounds(),{padding:[20,20]})}else if(pts.length)map.setView([LA[pts[0]],LO[pts[0]]],12);setTimeout(()=>{map.invalidateSize();lbls(map,lay)},80)}
const gk=i=>G.by==='all'?0:G.by==='distrito'?C.distrito[i]+'|'+C.provincia[i]+'|'+C.departamento[i]:C.periodo_sae[i]+'|'+C.unidad_territorial[i]+'|'+C[G.by][i];/* llave única: periodo_sae + unidad_territorial + ITEM/COMITÉ */
const sameGrp=(i,k)=>gk(i)==k;
/* ---------- fichas ---------- */
let QS='',fmap,flay,fhl,FM=[];const gm=i=>LA[i]<-0.5&&LA[i]>-19&&LO[i]<-68&&LO[i]>-82;
T.fic=()=>{if(fmap){fmap.remove();fmap=null}return`<div class=card><h3>Mapa de servicios educativos (SSEE)<small>Clic en un punto para abrir su ficha</small></h3><div id=fmap style="height:420px"></div></div><div class=card><h3>Fichas por SSEE</h3><input id=q placeholder="Buscar por nombre, código modular/local, departamento, provincia o distrito…" value="${QS}" autocomplete=off><div id=fres style="margin-top:12px"></div></div>`};
function fres(){const q=QS.trim().toLowerCase(),a=[];for(const i of ix(0)){if(!q||v('nombre_ie',i).toLowerCase().includes(q)||v('cod_modular',i).includes(q)||v('cod_local',i).includes(q)||v('departamento',i).toLowerCase().includes(q)||v('provincia',i).toLowerCase().includes(q)||v('distrito',i).toLowerCase().includes(q)){a.push(i);if(a.length>=4000)break}}FM=a;
 $('#fres').innerHTML=`<div class=tw><table class=tl><thead><tr><th>Cód. modular</th><th>Servicio educativo</th><th>Nivel</th><th>Departamento</th><th>Provincia</th><th>Distrito</th><th>Usuarios</th><th>Ficha 2025</th></tr></thead><tbody>${a.slice(0,100).map(i=>`<tr data-f=${i}><td>${v('cod_modular',i)}</td><td>${v('nombre_ie',i)}</td><td>${v('nivel',i)}</td><td>${v('departamento',i)}</td><td>${v('provincia',i)}</td><td>${v('distrito',i)}</td><td>${fmt(U[i])}</td><td>${hasF(i)?'<span class="pill ok">Sí</span>':'<span class="pill no">No</span>'}</td></tr>`).join('')}</tbody></table></div><p class=meta>${a.length>100?'Tabla: primeros 100 de '+(a.length>=4000?'4 000+':fmt(a.length))+' resultados. ':fmt(a.length)+' resultado(s). '}El mapa muestra hasta 4 000 puntos; afine la búsqueda para ver menos.</p>`;drawF()}
const MK=new Map();
function lbls(m=fmap,ly=flay){if(!m||!ly)return;const z=m.getZoom(),bd=m.getBounds();let n=0;ly.eachLayer(l=>{if(!l._nm)return;l.unbindTooltip();const inb=z>=14&&n<120&&bd.contains(l.getLatLng());if(inb)n++;l.bindTooltip(l._nm,{permanent:inb,direction:'top',offset:[0,-4],className:'lbl'})})}
function drawF(){if(!window.L)return setTimeout(drawF,300);if(!fmap){const o=newMap('fmap');fmap=o.m;flay=o.l;fhl=L.layerGroup().addTo(fmap);fmap.on('moveend zoomend',()=>lbls())}
 flay.clearLayers();MK.clear();fhl.clearLayers();const ps=FM.filter(gm);ps.forEach(i=>{const k=L.circleMarker([LA[i],LO[i]],{radius:6,color:hasF(i)?'#059669':'#e11d48',weight:1.5,fillOpacity:.8});k._nm=v('nombre_ie',i)+' · '+v('nivel',i)+' · '+U[i]+' usuarios';k.on('click',()=>{ficha(i);focusF(i)}).on('mouseover',()=>k.setStyle({radius:9,weight:3})).on('mouseout',()=>k.setStyle({radius:6,weight:1.5})).addTo(flay);MK.set(i,k)});
 if(ps.length)fmap.fitBounds(L.latLngBounds(ps.map(i=>[LA[i],LO[i]])),{padding:[25,25],maxZoom:16});setTimeout(()=>{fmap.invalidateSize();lbls()},80)}
function focusF(i,pulse){const f=tab==='fic',m=f?fmap:map,hl=f?fhl:ghl;if(!m||!hl||!gm(i))return;hl.clearLayers();L.circleMarker([LA[i],LO[i]],{radius:15,color:'#f59e0b',weight:3,fillOpacity:.25}).addTo(hl);if(!pulse)m.setView([LA[i],LO[i]],Math.max(m.getZoom(),16))}
let ghl;function verMapa(i){const f=tab==='fic',m=f?fmap:map;if(!m||!gm(i))return;if(innerWidth<900)$('#ficha').hidden=true;m.invalidateSize();let hl=f?fhl:(ghl=ghl&&m.hasLayer(ghl)?ghl:L.layerGroup().addTo(m));hl.clearLayers();
 const h=L.circleMarker([LA[i],LO[i]],{radius:14,color:'#f59e0b',weight:3,fillOpacity:.25}).bindPopup('<b>'+v('nombre_ie',i)+'</b>').addTo(hl);m.setView([LA[i],LO[i]],17);h.openPopup();$(f?'#fmap':'#map').scrollIntoView({behavior:'smooth',block:'center'})}
let byIE;
function fdata(i){if(!byIE){byIE=new Map();for(let j=0;j<N;j++){const k=C.cod_modular[j]*128+C.anexo[j];(byIE.get(k)||byIE.set(k,[]).get(k)).push(j)}}
 const fi=hasF(i),yn=x=>x==='Si'?'Sí':x||'—',st=(c,lab)=>{const x=v(c,i);return x===''?'—':lab[+x]},mt=m=>['co','al','cm'].map(s=>(v(MC[m][s],i)||'—').replace(/^\d+\.\s*/,'')).join(' / ');
 const S=[['Ubicación',[['Unidad territorial',v('unidad_territorial',i)],['Departamento / Provincia',v('departamento',i)+' / '+v('provincia',i)],['Distrito',v('distrito',i)],['Área',v('area',i)],['Cód. local',v('cod_local',i)],['Coordenadas',gm(i)?LA[i]+', '+LO[i]:'Sin coordenadas']]],
 ['Atención SAE · '+v('periodo_sae',i),[['Usuarios',fmt(U[i])],['Grupo de usuarios',v('rango_usuarios',i)],['Comité',v('comite',i)],['Item',v('item',i)],['Modalidad',v('modalidad',i)],['Forma de atención',v('forma_atencion',i)],['Tipo de ración',v('tipo_racion',i)],['Grupo SAE / Educunas',v('grupo_sae_educunas',i)]]],
 ['Infraestructura · información 2025',[['Ficha de Infraestructura 2025',fi?'Sí tiene':'No tiene'],...(fi?[['Kit de menaje',st('kitmenaje',KIT)],['Kit de cocina',st('kitcocina',KIT)],['Kit de mobiliario',st('kitmobiliario',KIT)],['Ambiente de cocina',st('ambientecocina',AMB)],['Ambiente de almacén',st('ambientealmacen',AMB)],['Ambiente de comedor',st('ambientecomedor',AMB)],['Abastecimiento de agua',v('abastecimiento_agua_por',i)],['Servicio higiénico conectado a',v('servicio_higienico_conectado_a',i)],['Alumbrado proviene de',v('alumbrado_proviene_de',i)],['Piso (cocina / almacén / comedor)',mt('piso')],['Pared (cocina / almacén / comedor)',mt('pared')],['Techo (cocina / almacén / comedor)',mt('techo')],['Cocina óptima',opt(i)?'Sí':'No'],['Agua / desagüe / electricidad adecuados',[v('agua_adecuada',i),v('desague_adecuado',i),v('electricidad_adecuada',i)].map(yn).join(' / ')]]:[['Estado de la infraestructura','Sin Ficha 2025: no hay datos']])]],
 ['Presencia por periodo',byIE.get(C.cod_modular[i]*128+C.anexo[i]).map(j=>[v('periodo_sae',j),fmt(U[j])+' usuarios'])]];return{fi,S}}
function ficha(i){const{fi,S}=fdata(i),ok=gm(i),L=(a,b)=>`<div class=li><span>${a}</span><span>${b===''||b==null?'—':b}</span></div>`;
 $('#ficha').innerHTML=`<header><button class=x onclick="$('#ficha').hidden=true" title=Cerrar>✕</button><span class=tag>Ficha de servicio educativo (SSEE)</span><h2 style="font-size:1.1rem">${v('nombre_ie',i)}</h2><small>${v('nivel',i)} · Cód. modular ${v('cod_modular',i)} · Anexo ${v('anexo',i)}</small>
 <div class=acts><button class=btn data-a=map ${ok?'':'disabled'}>📍 Ver mapa</button><a class=btn ${ok?`href="https://www.google.com/maps?q=${LA[i]},${LO[i]}" target=_blank rel=noopener`:'style="opacity:.5;pointer-events:none"'}>🌐 Google Maps</a><button class=btn data-a=doc>📄 Word</button><button class=btn data-a=x>Cerrar</button></div></header>`
 +S.map(([t,r])=>`<section><h4>${t}</h4>${r.map(([a,b])=>L(a,a==='Ficha de Infraestructura 2025'?`<span class="pill ${fi?'ok':'no'}">${b}</span>`:b)).join('')}</section>`).join('');
 $('#ficha').onclick=e=>{const a=e.target.dataset.a;if(a==='x')$('#ficha').hidden=true;if(a==='map')verMapa(i);if(a==='doc')fichaDoc(i)};$('#ficha').hidden=false}
function fichaDoc(i){const{S}=fdata(i);dl('\ufeff'+`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><style>${CSS}</style></head><body><p style="color:#b45309"><b>En un clic · SAE — Ficha de servicio educativo (SSEE)</b></p><h1>${v('nombre_ie',i)}</h1><p>${v('nivel',i)} · Cód. modular ${v('cod_modular',i)} · Anexo ${v('anexo',i)} · Periodo ${v('periodo_sae',i)}</p>${S.map(([t,r])=>`<h2>${t}</h2><table width="100%">${r.map(([a,b])=>`<tr><td width="42%"><b>${a}</b></td><td style="text-align:${isNum(b)?'right':'left'}">${b===''?'—':b}</td></tr>`).join('')}</table>`).join('')}<p><i>Infraestructura: información de la Ficha de Infraestructura 2025. Generado: ${new Date().toLocaleString('es-PE')}</i></p></body></html>`,'Ficha_'+v('cod_modular',i)+'_'+v('periodo_sae',i)+'.doc','application/msword')}
/* ---------- helpers v2 ---------- */
const tcase=s=>s?s.charAt(0)+s.slice(1).toLowerCase().replace(/_/g,' / '):'Sin dato';
const mdl=i=>v('modalidad',i)||'Sin dato',rac=i=>v('tipo_racion',i)||'Sin dato',nvl=i=>tcase(v('nivel',i)),ara=i=>v('area',i)||'Sin dato';
const norF=i=>{const x=v('forma_atencion',i);return!x?'COMIDA LISTA PARA CONSUMO':/CONCESI/.test(x)?'CONCESIÓN':/SUBVENCION/.test(x)?'TRANSFERENCIA DE SUBVENCIÓN ECONÓMICA':x};
const cntK=(ix,fn)=>{const m=new Map();for(const i of ix){const k=fn(i);let o=m.get(k);if(!o)m.set(k,o=[k,0,0]);o[1]++;o[2]+=U[i]}return[...m.values()].sort((a,b)=>b[1]-a[1])};
const RG=[[1,1,'1'],[2,9,'2 - 9'],[10,24,'10 - 24'],[25,49,'25 - 49'],[50,74,'50 - 74'],[75,99,'75 - 99'],[100,249,'100 - 249'],[250,499,'250 - 499'],[500,750,'500 - 750'],[751,1000,'751 - 1,000'],[1001,2000,'1,001 - 2,000'],[2001,1e9,'2,001 a más']];
function rngRows(ix){const r=RG.map(g=>[g[2],0,0]),sd=['Sin datos',0,0];for(const i of ix){const x=U[i],k=x>0?RG.findIndex(g=>x>=g[0]&&x<=g[1]):-1,o=k<0?sd:r[k];o[1]++;o[2]+=x}return[...r,sd]}
function pv(ix,rf,cf){const M=new Map(),cs=new Set();for(const i of ix){const r=rf(i),c=cf(i);cs.add(c);let m=M.get(r);if(!m)M.set(r,m=new Map());let o=m.get(c);if(!o)m.set(c,o=[0,0]);o[0]++;o[1]+=U[i]}return{M,cs:[...cs].sort()}}
function mt(t,first,ix,rf,cf,sf){const nc=!cf;cf=cf||(()=>'T');
 const P=pv(ix,sf?i=>rf(i)+'\u0001'+sf(i):rf,cf),cs=nc?[]:P.cs,GM=sf?pv(ix,rf,cf).M:null,TM=pv(ix,()=>'T',cf).M.get('T');
 const cl=m=>{let a=0,b=0;if(m)for(const o of m.values()){a+=o[0];b+=o[1]}return[...cs.flatMap(c=>{const o=m&&m.get(c);return o?[fmt(o[0]),fmt(o[1])]:['','']}),fmt(a),fmt(b)]},L=[];
 if(sf){for(const g of[...GM.keys()].sort()){L.push([g,cl(GM.get(g)),'gp']);for(const k of[...P.M.keys()].filter(k=>k.startsWith(g+'\u0001')).sort())L.push([k.split('\u0001')[1],cl(P.M.get(k)),'sb'])}}
 else for(const k of[...P.M.keys()].sort())L.push([k,cl(P.M.get(k)),'']);
 if(TM)L.push(['TOTAL',cl(TM),'tt']);
 const h=[first,...cs.flatMap(c=>[c+' · SSEE',c+' · Usuarios']),'TOTAL · SSEE','TOTAL · Usuarios'],G=[...cs,'TOTAL'];
 return{t,h,rows:L.map(l=>[l[0],...l[1]]),html:`<div class=tw><table class=mt><thead><tr><th rowspan=2>${first}</th>${G.map(c=>`<th colspan=2 class=cg>${c}</th>`).join('')}</tr><tr>${G.map(()=>'<th>SSEE</th><th>Usuarios</th>').join('')}</tr></thead><tbody>${L.map(l=>`<tr class="${l[2]}"><td>${l[0]}</td>${l[1].map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}}
const mcard=o=>{dat(o.t,o.h,o.rows);return`<div class=card><h3>${o.t}</h3>${o.html}</div>`};
/* cobertura y brecha (cobertura.js · periodo 2026-II) */
const CBO=['INICIAL','PRIMARIA','SECUNDARIA_FAD','SECUNDARIA_JEC','SECUNDARIA_IND'];
function cobSel(){const W=window.COBERTURA;if(!W)return{err:'No se cargó cobertura.js (ejecute build_cobertura.py).'};const per=Dd.periodo_sae[sel.periodo_sae];
 const dif=per!==W.periodo;
 const g=c=>sel[c]>=0?Dd[c][sel[c]].toUpperCase():'',ut=g('unidad_territorial'),dp=g('departamento'),nv=sel.nivel>=0?Dd.nivel[sel.nivel].split('_')[0]:'';
 const rows=W.rows.filter(r=>(!ut||r[0]===ut)&&(!dp||r[1]===dp||(dp==='LIMA'&&r[1].startsWith('LIMA'))||(dp==='CALLAO'&&r[1].startsWith('LIMA METRO')))&&(!nv||r[2].startsWith(nv)));
 const ign=[['grupo_sae_educunas','grupo'],['provincia','provincia'],['distrito','distrito'],['area','área'],['modalidad','modalidad'],['tipo_racion','ración']].filter(([c])=>sel[c]>=0).map(x=>x[1]);
 return{rows,ign:ign.join(', '),dif,pw:W.periodo}}
function cobT(t,first,rows,ki,order){const m=new Map();for(const r of rows){let o=m.get(r[ki]);if(!o)m.set(r[ki],o=[0,0,0,0]);const j=r[3]?2:0;o[j]+=r[4];o[j+1]+=r[5]}
 const ks=[...m.keys()].sort(order?(a,b)=>{const x=order.indexOf(a),y=order.indexOf(b);return(x<0?99:x)-(y<0?99:y)||(a<b?-1:1)}:undefined),z=x=>x?fmt(x):'';
 const line=(k,o)=>[k,fmt(o[0]),fmt(o[1]),z(o[2]),z(o[3]),fmt(o[0]+o[2]),fmt(o[1]+o[3]),pc(o[0],o[0]+o[2]),pc(o[1],o[1]+o[3])],T=[0,0,0,0];ks.forEach(k=>m.get(k).forEach((x,j)=>T[j]+=x));
 const rw=[...ks.map(k=>line(k,m.get(k))),line('Total general',T)],h=[first,'Cobertura · SSEE','Cobertura · Usuarios','Brecha · SSEE','Brecha · Usuarios','Total SSEE','Total usuarios','% cobertura SSEE','% cobertura usuarios'],gp=j=>j===3||j===4?' class=gap':'';
 return{t,h,rows:rw,tot:T,html:`<div class="tw ns"><table class=mt><thead><tr>${h.map((x,j)=>`<th${gp(j)}>${x}</th>`).join('')}</tr></thead><tbody>${rw.map((r,j)=>`<tr class="${j===rw.length-1?'tt':''}">${r.map((x,q)=>`<td${gp(q)}>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}}
function cobCards(){const c=cobSel(),T0='Cobertura y brecha (listado de SSEE 2.º tramo)';if(c.err)return`<div class=card><h3>${T0}</h3><div class=note>⚠ ${c.err}</div></div>`;
 return`<div class=note>Fuente: Padrón de SSEE MINEDU, Escale 02.09.2026; BD SIAGIE 05.08.2026; BDPI MINCUL enero 2026.${c.dif?' La base de cobertura corresponde al periodo '+c.pw+' y no varía con el filtro de periodo.':''}${c.ign?' Filtros sin efecto en cobertura: '+c.ign+'.':''}</div>`
 +[cobT(T0+' · por nivel','Nivel',c.rows,2,CBO),cobT(T0+' · por departamento','Departamento',c.rows,1)].map(mcard).join('')}
T.tab=ix=>`<div class=note>Cuadros dinámicos según los filtros activos (periodo ${Dd.periodo_sae[sel.periodo_sae]}). Todos se incluyen en las exportaciones Word / Excel. Las tablas de cobertura y brecha están ahora en el <b>Resumen ejecutivo</b>. <b>Turno:</b> el padrón cargado no trae esa variable; para el cuadro «Nivel educativo y turno» hay que añadir la columna a build_datos.py.</div>`
 +mcard(mt('1.2 Modalidades y formas de atención','Modalidad / forma de atención',ix,mdl,null,norF))+mcard(mt('Nivel educativo y modalidad','Nivel educativo',ix,nvl,mdl))+mcard(mt('Nivel educativo y tipo de ración','Nivel educativo',ix,nvl,rac))+mcard(mt('Nivel educativo, área y tipo de ración','Área / nivel educativo',ix,ara,rac,nvl));
/* ---------- ayuda memoria ---------- */
let AMT='Mejoras implementadas: Para el segundo tramo de atención se ha ampliado la diversidad de alimentos considerando la pertinencia y diversidad cultural.\nResultados o avances: Los servicios educativos cuentan con modalidades y formas de atención asignadas.\nAspectos que requieren atención: Seguimiento y monitoreo permanente para la implementación de las modalidades y formas de atención.\nInnovación: Se cuenta con la nota técnica aprobada para la implementación del piloto PAE Amazónico en servicios educativos priorizados de Amazonas, Loreto, San Martín, Ucayali y Madre de Dios.';
function amDoc(ix){const per=Dd.periodo_sae[sel.periodo_sae],n=ix.length,u=ix.reduce((a,i)=>a+U[i],0),loc=['unidad_territorial','departamento','provincia','distrito'].filter(c=>sel[c]>=0).map(c=>lb(Dd[c][sel[c]])).join(' · ')||'NACIONAL',oth=['grupo_sae_educunas','area','nivel','modalidad','tipo_racion'].filter(c=>sel[c]>=0).map(c=>lb(Dd[c][sel[c]])).join(' · ');
 let h=`<h1>AYUDA MEMORIA</h1><p class=sub><b>${loc} (SAE)</b>${oth?' · '+oth:''}</p>`;if(!n)return h+'<p>No hay servicios educativos con los filtros seleccionados.</p>';
 const dep=new Set,prv=new Set,dis=new Set,com=new Set;for(const i of ix){const d=C.departamento[i],p=d+'|'+C.provincia[i];dep.add(d);prv.add(p);dis.add(p+'|'+C.distrito[i]);if(v('comite',i))com.add(C.comite[i])}
 const mo=cntK(ix,mdl).sort((a,b)=>b[2]-a[2]),ni=cntK(ix,nvl).sort((a,b)=>b[2]-a[2]),ar=cntK(ix,ara).sort((a,b)=>b[2]-a[2]),ra=cntK(ix,rac).sort((a,b)=>b[2]-a[2]).slice(0,3),col=['#d97706','#059669','#2563eb'];
 const cb=cobSel();let cov='No disponible para este periodo: la base de cobertura corresponde solo a 2026-II.';if(!cb.err){let c=0,b=0;cb.rows.forEach(r=>r[3]?b+=r[4]:c+=r[4]);cov=`${fmt(c)} de ${fmt(c+b)} SSEE del listado del 2.º tramo (${pc(c,c+b)}); brecha de ${fmt(b)} SSEE${cb.dif?' (base de cobertura: '+cb.pw+')':''}`}
 const sx=a=>a.map(r=>`${tcase(r[0])} (${fmt(r[1])} SSEE; ${fmt(r[2])} usuarios, ${pc(r[2],u)})`).join('; ');
 h+=`<h2>1. PRESTACIÓN DEL SERVICIO ALIMENTARIO ESCOLAR ${per}</h2><h3>1.1 Cobertura de atención</h3><ul><li>N.º de servicios educativos (SSEE): <b>${fmt(n)}</b></li><li>N.º de usuarios: <b>${fmt(u)}</b> usuarios</li><li>Porcentaje de cobertura: ${cov}</li></ul>`
 +`<h3>Resumen narrativo</h3><p>Para el periodo ${per}, el Servicio Alimentario Escolar (SAE) atiende a <b>${fmt(u)}</b> usuarios en <b>${fmt(n)}</b> servicios educativos (SSEE), con presencia en ${fmt(dis.size)} distritos (${pc(dis.size,1891)} de los 1,891 distritos del país) de ${fmt(prv.size)} provincias en ${fmt(dep.size)} departamentos${com.size?', a cargo de '+fmt(com.size)+' comités':''}.</p>`
 +mo.map((m,k)=>{const f=cntK(ix.filter(i=>mdl(i)===m[0]),norF);return`<p><span style="color:${col[k%3]}">●</span> <b>${tcase(m[0])}.</b> Atiende a ${fmt(m[2])} usuarios (${pc(m[2],u)}) en ${fmt(m[1])} SSEE. Formas de atención: ${f.map(x=>`${tcase(x[0])} (${fmt(x[1])} SSEE; ${fmt(x[2])} usuarios)`).join('; ')}.</p>`}).join('')
 +`<p><b>Por nivel educativo:</b> ${sx(ni)}.</p><p><b>Por ámbito:</b> ${sx(ar)}.</p><p><b>Tipos de ración predominantes:</b> ${sx(ra)}.</p>`
 +`<h3>1.2 Modalidades de atención</h3><ul>${mo.map(m=>`<li>${tcase(m[0])}: ${fmt(m[1])} SSEE, ${fmt(m[2])} usuarios (${cntK(ix.filter(i=>mdl(i)===m[0]),norF).map(x=>tcase(x[0])+': '+fmt(x[1])+' SSEE').join('; ')})</li>`).join('')}</ul>`
 +[mt('Nivel educativo y modalidad','Nivel educativo',ix,nvl,mdl),mt('Nivel educativo y tipo de ración','Nivel educativo',ix,nvl,rac),mt('Nivel educativo, área y tipo de ración','Área / nivel educativo',ix,ara,rac,nvl)].map(o=>`<h4>${o.t}</h4>${o.html}`).join('')
 +`<h3>1.3 Principales mejoras en el SAE ${per}</h3><ul>${AMT.split('\n').filter(x=>x.trim()).map(x=>{const j=x.indexOf(':');return`<li>${j>0&&j<60?`<b>${x.slice(0,j)}:</b>${x.slice(j+1)}`:x}</li>`}).join('')}</ul>`;return h}
T.am=ix=>`<div class=card><h3>Ayuda memoria<small>se recalcula con los filtros activos</small></h3><div class=acts2><button class=btn id=amdoc>📄 Descargar ayuda memoria (Word)</button></div><label style="display:block;margin-top:12px">Sección 1.3 · Principales mejoras (una viñeta por línea, formato «Título: texto»)<textarea id=amt rows=6>${AMT}</textarea></label></div><div class="card doc" id=ampv>${amDoc(ix)}</div>`;
/* ======== v3 · Word (alineación numérica y orientación), análisis de cocinas óptimas y EDUCUNAS 2026 ======== */
const isNum=s=>/^[+\-−]?\d[\d.,]*%?$/.test(String(s).trim()),nf=x=>typeof x==='number'?fmt(x):(x==null?'':x);
const PGP='size:595.3pt 841.9pt;margin:56.7pt 50pt 56.7pt 50pt',PGL='size:841.9pt 595.3pt;mso-page-orientation:landscape;margin:50pt 42pt 50pt 42pt';
const wcols=t=>((t.querySelector('tbody tr')||t.querySelector('tr')||{children:[]}).children.length);
/* Da formato Word a una tabla HTML: bordes, cifras a la derecha, columnas «Brecha» tenues, filas de total */
function wfix(html){const d=document.createElement('div');d.innerHTML=html;
 d.querySelectorAll('table').forEach(t=>{t.setAttribute('border','1');t.setAttribute('cellspacing','0');t.setAttribute('cellpadding','3');t.style.cssText='border-collapse:collapse;width:100%';
  const multi=t.querySelectorAll('thead tr').length>1,b0=t.querySelector('tbody tr'),fs=wcols(t)>7?'8.5pt':'10pt';
  t.querySelectorAll('tr').forEach(r=>{const cls=r.className||'',tt=/\btt\b/.test(cls),gp=/\bgp\b/.test(cls);
   [...r.children].forEach((c,j)=>{const th=c.tagName==='TH',gap=c.classList.contains('gap'),tx=c.textContent.trim();let al;
    if(th){const bt=b0&&b0.children[j]?b0.children[j].textContent.trim():'';al=c.classList.contains('cg')?'center':multi?(r.rowIndex===0?'left':'right'):(j===0?'left':(bt!==''&&!isNum(bt)&&bt!=='—'?'left':'right'))}
    else al=j===0||!(tx===''||tx==='—'||isNum(tx))?'left':'right';
    const bg=th?(gap?'#EADFC0':'#dbe8f7'):tt?(gap?'#E9DFC2':'#dbe8f7'):gap?'#FAF4E4':gp?'#eaf0fb':'';
    c.style.cssText=`border:1px solid #94a3b8;padding:3px 6px;font-size:${fs};text-align:${al};${bg?'background:'+bg+';':''}${th||tt||gp?'font-weight:bold;':''}${th?'color:#0b1f47;':''}`})})});
 return d.innerHTML}
const wT=(h,rows)=>wfix(`<table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${nf(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`);
/* Arma el .doc con secciones: cada bloque ancho (>7 columnas) va en una sección horizontal */
function wordDoc(items,extra=''){const S=[];let pend='';
 for(const it of items){if(it.land===null){pend+=it.html;continue}const h=pend+it.html;pend='';const l=S[S.length-1];if(l&&l.land===it.land)l.html+=h;else S.push({land:it.land,html:h})}
 if(pend){if(S.length)S[S.length-1].html+=pend;else S.push({land:false,html:pend})}
 const pg=S.map((s,k)=>`@page WordSection${k+1}{${s.land?PGL:PGP}}div.WordSection${k+1}{page:WordSection${k+1}}`).join('');
 return`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View></w:WordDocument></xml><![endif]--><style>${CSS}${extra}${pg}</style></head><body>${S.map((s,k)=>(k?'<span><br clear=all style="page-break-before:always;mso-break-type:section-break"></span>':'')+`<div class=WordSection${k+1}>${s.html}</div>`).join('')}</body></html>`}
const rep=doc=>{const hd=`<h1>En un clic · SAE — ${TT[tab]}</h1><p>Filtros: ${filtros()||'ninguno'} · Generado: ${new Date().toLocaleString('es-PE')}</p><p><i>Infraestructura: información de la Ficha de Infraestructura 2025.</i></p>`,
 blk=d=>`<h2>${d.t}</h2>`+wT(d.h,d.r)+(d.n?d.n.map(x=>`<p style="font-size:8.5pt;margin:2px 0">${x}</p>`).join(''):'');
 if(doc)return wordDoc([{land:null,html:hd},...R.map(d=>({land:d.h.length>7,html:blk(d)}))]);
 return`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"><style>${CSS}</style></head><body>${hd}${R.map(blk).join('')}</body></html>`};
function amWord(){const box=document.createElement('div');box.innerHTML=amDoc(ix(0));const items=[];let heads='';
 [...box.children].forEach(el=>{if(el.tagName==='H4'){heads+=el.outerHTML;return}const t=el.querySelector&&el.querySelector('table');
  if(t)items.push({land:wcols(t)>7,html:heads+wfix(el.outerHTML)});else items.push({land:false,html:heads+el.outerHTML});heads=''});
 items.push({land:false,html:`<p><i>Generado: ${new Date().toLocaleString('es-PE')} · Fuente: Listado de Servicios Educativos PC 2026–2027.</i></p>`});
 dl('\ufeff'+wordDoc(items,'h1{text-align:center;font-size:20pt}.sub{text-align:center}h3{color:#0b1f47;font-size:12pt}h4{font-size:10.5pt;margin:12px 0 3px}'),'Ayuda_memoria_SAE_'+Dd.periodo_sae[sel.periodo_sae]+'.doc','application/msword')}

/* ---------- Infraestructura: análisis de cocinas óptimas (periodo_sae = 2026-II) ---------- */
const INFRA_B=67055;/* registros de BD_Infraestructura 2025 (corte 19.12.2025): dato de referencia, no está en el padrón */
const IV=[['cuenta_con_cocina','Cuenta con ambiente de cocina (exclusivo o compartido)'],['piso_adecuado','Piso adecuado en cocina'],['pared_adecuada','Paredes adecuadas en cocina'],['techo_adecuado','Techo adecuado en cocina'],['cuenta_cocina_adecuada','Cocina adecuada (ambiente + piso + paredes + techo)'],['agua_adecuada','Agua adecuada (red pública)'],['desague_adecuado','Desagüe adecuado (red pública)'],['electricidad_adecuada','Electricidad adecuada (red pública)'],['cuenta_ss_basicos_adecuada','Cuenta con los 3 servicios básicos'],['cocinas_adecu_ss_basicos','Cocina adecuada y con 3 servicios básicos'],['menaje_buen_estado','Menaje en buen estado'],['kitcocina_buen_estado','Kit de cocina en buen estado'],['kitmobiliario_buen_estado','Kit de mobiliario en buen estado'],['menaje_uten_buen_estado','Menaje, kit de cocina y utensilios en buen estado'],['cocina_optima','Cocina óptima']];
function infraFlags(i){const Y=c=>v(c,i)==='Si',cc=v('ambientecocina',i)==='1'||v('ambientecocina',i)==='2',pi=/^[1-5]\./.test(v(MC.piso.co,i)),pa=/^[1-8]\./.test(v(MC.pared.co,i)),te=/^[1-6]\./.test(v(MC.techo.co,i)),
 ss=Y('agua_adecuada')&&Y('desague_adecuado')&&Y('electricidad_adecuada'),cad=Y('cuenta_cocina_adecuada');
 return{cuenta_con_cocina:cc,piso_adecuado:pi,pared_adecuada:pa,techo_adecuado:te,cuenta_cocina_adecuada:cad,agua_adecuada:Y('agua_adecuada'),desague_adecuado:Y('desague_adecuado'),electricidad_adecuada:Y('electricidad_adecuada'),cuenta_ss_basicos_adecuada:ss,cocinas_adecu_ss_basicos:cad&&ss,menaje_buen_estado:Y('menaje_buen_estado'),kitcocina_buen_estado:Y('kitcocina_buen_estado'),kitmobiliario_buen_estado:Y('kitmobiliario_buen_estado'),menaje_uten_buen_estado:Y('menaje_buen_estado')&&Y('kitcocina_buen_estado')&&Y('kitmobiliario_buen_estado'),cocina_optima:opt(i)}}
function anCocinas(){const per=Dd.periodo_sae.indexOf('2026-II');if(per<0)return'';
 const I=ix(1,per),n=I.length,u=I.reduce((a,i)=>a+U[i],0),A={};IV.forEach(([k])=>A[k]=[0,0]);let un=0,uu=0;
 for(const i of I){const f=infraFlags(i);for(const k in A)if(f[k]){A[k][0]++;A[k][1]+=U[i]}if(v('iieedetalle',i)!==''){un++;uu+=U[i]}}
 const nof=!FIL.some(([c])=>c!=='periodo_sae'&&sel[c]>=0),D='—',L=[],add=(cod,d,cl,a,b,p)=>L.push([cod,d,cl,a,b,p]);
 add('A','Listado 2026 II','gp',n,u,0);add('B','Base Infraestructura','gp',nof?INFRA_B:null,null,0);
 add('','Resultado de unión de las bases A + B','',un,uu,0);add('','No se unen las bases A + B','',nof?(n-un)+(INFRA_B-un):null,null,0);
 add('','Solo en base A (sin información de infraestructura)','',n-un,u-uu,0);add('','Solo en base B (no se encuentra en el Listado 2026 II)','',nof?INFRA_B-un:null,null,0);
 const blk=(cod,t,y,k,no)=>{add(cod,t,'gp',n,u,1);add('',y,'',A[k][0],A[k][1],1);add('',no,'',n-A[k][0],u-A[k][1],1)};
 blk('C','Estado de cocinas','Con cocina adecuada 1/','cuenta_cocina_adecuada','Sin cocina adecuada');
 blk('D','Estado de servicios básicos','Cuenta con 3 servicios básicos 2/','cuenta_ss_basicos_adecuada','No cuenta con 3 servicios básicos');
 blk('E','Cocina en condiciones adecuadas y con tres servicios básicos','Cocina en condiciones adecuadas y con tres servicios básicos','cocinas_adecu_ss_basicos','No cuenta con condiciones adecuadas o con 3 servicios');
 blk('F','Menaje y utensilios de cocina en buen estado','Menaje, kit de cocina y utensilios de cocina en buen estado','menaje_uten_buen_estado','No cuenta con menaje, kit de cocina y utensilios de cocina en buen estado');
 blk('G','Cocinas óptimas','Cocina en condiciones adecuadas y con tres servicios básicos; incluye menaje y utensilios de cocina en buen estado','cocina_optima','No se consideran cocinas óptimas');
 const rows=L.map(([cod,d,cl,a,b,p])=>[cod,d,a==null?D:fmt(a),p&&a!=null?pc(a,n):'',b==null?D:fmt(b),p&&b!=null?pc(b,u):'']),
 notes=['1/ Las cocinas cuentan con: ambiente cocina (exclusiva y/o compartida) e infraestructura (piso, paredes y techo adecuados). Con infraestructura (Piso: parquet, madera pulida, vinílico, pisopak, loseta, cerámico, cemento o madera entablada; Paredes: ladrillo, concreto armado, piedra, sillar con cal, sillar con cemento, fibra de cemento, Eternit, adobe, tapial, quincha, piedra con barro, madera o estera; y Techo: concreto armado, madera, tejas, fibra de cemento, Eternit, calamina, caña o carrizo).','2/ Se consideran los servicios agua, desagüe y electricidad con conexión a red pública.','Fuente: Listado SAE 2026 II tramo y BD_Infraestructura 2025 (corte 19.12.2025).','Elaboración: Subunidad de Innovación y Calidad - PAE.'],
 T1='Análisis de SSEE con cocinas óptimas · periodo 2026-II';
 dat(T1,['Cod','Descripción','Total SSEE · Cantidad','Total SSEE · %','Usuarios · Cantidad','Usuarios · %'],rows,notes);
 const t1=`<div class=card><h3>${T1}<small>Listado SAE 2026-II${nof?'':' · con los filtros activos'}</small></h3><div class="tw ns"><table class="mt an"><thead><tr><th rowspan=2>Cod</th><th rowspan=2>Descripción</th><th colspan=2 class=cg>Total SSEE</th><th colspan=2 class=cg>Usuarios</th></tr><tr><th>Cantidad</th><th>%</th><th>Cantidad</th><th>%</th></tr></thead><tbody>${rows.map((r,j)=>`<tr class="${L[j][2]}">${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class=fn>${notes.map(x=>`<p>${x}</p>`).join('')}</div></div>`;
 const rows2=IV.map(([k,l])=>{const a=A[k];return[k,l,fmt(a[0]),pc(a[0],n),fmt(a[1]),pc(a[1],u),fmt(n-a[0]),pc(n-a[0],n)]});
 return`<div class=note>🍳 <b>Análisis de cocinas óptimas.</b> Esta sección usa siempre el listado <b>2026-II</b> (ignora el filtro de periodo) y respeta los demás filtros.${nof?'':' Las filas B y «Solo en base B» solo se muestran sin filtros, porque la base de infraestructura no está en el padrón.'} Las variables <i>cuenta_con_cocina, piso/pared/techo_adecuado, cuenta_ss_basicos_adecuada, cocinas_adecu_ss_basicos y menaje_uten_buen_estado</i> se construyen a partir de ambiente de cocina, materiales y variables «adecuadas» de la base.</div>`+t1
 +tbl('Indicadores de cocina e infraestructura por variable · periodo 2026-II',['Variable','Descripción','SSEE · Sí','%','Usuarios · Sí','%','SSEE · No / sin dato','%'],rows2,null,500,{ns:1,c:'tx'})}

/* ---------- EDUCUNAS 2026 (educunas.js ← build_educunas.py) ---------- */
const ED=window.EDUCUNAS,EC=ED&&ED.c,nzs=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();let EDN;
const COC=[['cuenta_con_cocina','Cuenta con ambiente de cocina'],['cocina_ventilada','Cocina ventilada'],['cocina_distante_sshh','Cocina a distancia adecuada de SS.HH.'],['cuenta_fuente_agua','Cuenta con fuente de agua'],['cuenta_lavadero','Cuenta con lavadero'],['ventanas_mosquiteras_cocina','Ventanas con mallas mosquiteras'],['proteccion_acceso_cocina','Acceso con protección'],['cuenta_electricidad','Cuenta con electricidad'],['cuenta_artefacto_cocina','Cuenta con artefacto de cocina'],['cuenta_mesa_trabajo','Cuenta con mesa de trabajo'],['cuenta_ollas','Cuenta con ollas'],['cuenta_utensilios_cocina','Cuenta con utensilios mínimos']],
 ALM=[['cuenta_con_almacen','Cuenta con almacén'],['almacen_distante_sshh','Almacén a distancia adecuada de SS.HH.'],['ventanas_mosquiteras_almacen','Ventanas con mallas mosquiteras'],['proteccion_acceso_almacen','Acceso con protección'],['cuenta_equipamiento_almacen','Cuenta con equipamiento de almacén'],['cuenta_sistema_frio','Cuenta con refrigeradora y/o congeladora']],
 EALL=COC.concat(ALM),ESC=['estado_paredes_cocina','estado_techo_cocina','estado_piso_cocina'],ESA=['estado_paredes_almacen','estado_techo_almacen','estado_piso_almacen'],EL=['Adecuado','Regular','Crítico','No aplica','Sin dato'],EK=['#059669','#f59e0b','#e11d48','#94a3b8','#cbd5e1'];
function edIx(){if(!EC)return[];if(!EDN)EDN={ut:EC.ut.map(nzs),dep:EC.dep.map(nzs),prov:EC.prov.map(nzs),dis:EC.dis.map(nzs)};
 const f=[['unidad_territorial','ut'],['departamento','dep'],['provincia','prov'],['distrito','dis']].filter(([c])=>sel[c]>=0).map(([c,k])=>[k,nzs(Dd[c][sel[c]])]),a=[];
 for(let i=0;i<ED.n;i++)if(f.every(([k,x])=>EDN[k][i]===x))a.push(i);return a}
const eb=I=>I.reduce((a,i)=>a+EC.ben[i],0),kAd=i=>EC.cuenta_con_cocina[i]===1&&ESC.every(c=>EC[c][i]==='Adecuado'),kEq=i=>['cuenta_artefacto_cocina','cuenta_mesa_trabajo','cuenta_ollas','cuenta_utensilios_cocina'].every(c=>EC[c][i]===1),
 aAd=i=>EC.cuenta_con_almacen[i]===1&&EC.cuenta_equipamiento_almacen[i]===1&&ESA.every(c=>EC[c][i]==='Adecuado'),fOk=i=>EC.cuenta_sistema_frio[i]===1&&['Óptimo','Aceptable'].includes(EC.ref[i]),
 kIn=i=>kAd(i)&&kEq(i)&&EC.cuenta_fuente_agua[i]===1&&EC.cuenta_electricidad[i]===1,
 ebr=i=>EALL.reduce((s,[c])=>s+(EC[c][i]===0?1:0),0)+ESC.concat(ESA).reduce((s,c)=>s+(EC[c][i]==='Crítico'?1:0),0)+(EC.ref[i]==='Malo / inoperativo'?1:0)+(EC.mic[i]==='Malo / inoperativo'?1:0);
const cntE=(I,fn)=>{const m=new Map();for(const i of I){const k=fn(i);let o=m.get(k);if(!o)m.set(k,o=[k,0,0]);o[1]++;o[2]+=EC.ben[i]}return[...m.values()].sort((a,b)=>b[1]-a[1])};
function edMeta(){const I=edIx();return`<b>${fmt(I.length)}</b> SSEE EDUCUNAS · <b>${fmt(I.length?eb(I):0)}</b> beneficiarios · ${['unidad_territorial','departamento','provincia','distrito'].filter(c=>sel[c]>=0).map(c=>lb(Dd[c][sel[c]])).join(' · ')||'sin filtros de ubicación'}`}
function edCsv(){const I=edIx(),cs=Object.keys(EC),q=s=>'"'+String(s).replace(/"/g,'""')+'"';dl('\ufeff'+[cs.join(',')].concat(I.map(i=>cs.map(c=>q(EC[c][i])).join(','))).join('\n'),'EDUCUNAS_2026_filtrado.csv','text/csv')}
function plainT(t,h,rows,tot){dat(t,h,rows);return`<div class=card><h3>${t}</h3><div class="tw ns"><table class=mt><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map((r,j)=>`<tr class="${r._c||(tot&&j===rows.length-1?'tt':'')}">${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
T.edu=()=>{if(!EC)return`<div class=card><div class=note>⚠ No se cargó educunas.js. Genérelo con <b>python build_educunas.py EDUCUNAS_2026.xlsx educunas.js</b>.</div></div>`;
 const I=edIx(),n=I.length;if(!n)return`<div class=note>No hay SSEE de EDUCUNAS con los filtros de ubicación seleccionados.</div>`;
 const be=eb(I),yes=c=>I.filter(i=>EC[c][i]===1),no=c=>I.filter(i=>EC[c][i]===0),sec=I.reduce((a,i)=>a+EC.sec[i],0),dis=new Set(I.map(i=>EC.ubi?EC.ubi[i]:EC.dep[i]+EC.prov[i]+EC.dis[i])).size,
  yr=l=>l.map(([c,t])=>{const a=yes(c),m=no(c),o=n-a.length-m.length;return[t,a.length,eb(a),m.length,o,c]}),
  ynT=(t,l)=>plainT(t,['Condición','Sí · SSEE','%','No · SSEE','%','No aplica / sin dato','%','% cumplimiento*'],yr(l).map(r=>[r[0],fmt(r[1]),pc(r[1],n),fmt(r[3]),pc(r[3],n),fmt(r[4]),pc(r[4],n),pc(r[1],r[1]+r[3])])),
  stE=(t,c)=>stack(t,EL,EK,EL.map(l=>I.filter(i=>EC[c][i]===l).length),'EDUCUNAS 2026'),
  um=new Map();for(const i of I){const k=EC.ut[i];(um.get(k)||um.set(k,[]).get(k)).push(i)}
 const urow=(lab,ids)=>{const m=ids.length;return[lab,fmt(m),fmt(eb(ids)),pc(ids.filter(i=>EC.cuenta_con_cocina[i]===1).length,m),pc(ids.filter(kAd).length,m),pc(ids.filter(kEq).length,m),pc(ids.filter(aAd).length,m),pc(ids.filter(fOk).length,m),f1(ids.reduce((s,i)=>s+ebr(i),0)/m)]};
 const ur=[...um.entries()].sort((a,b)=>b[1].length-a[1].length).map(([k,ids])=>urow(k,ids));ur.push(urow('Total',I));
 const mf=new Map();for(const i of I){const a=EC.mod[i]||'SIN DATO',b=EC.forma[i];let g=mf.get(a);if(!g)mf.set(a,g=new Map());let o=g.get(b);if(!o)g.set(b,o=[0,0]);o[0]++;o[1]+=EC.ben[i]}
 const mr=[];for(const[a,g]of[...mf.entries()].sort((x,y)=>[...y[1].values()].reduce((s,o)=>s+o[0],0)-[...x[1].values()].reduce((s,o)=>s+o[0],0))){const sn=[...g.values()].reduce((s,o)=>s+o[0],0),sb=[...g.values()].reduce((s,o)=>s+o[1],0),r=[a,fmt(sn),fmt(sb),pc(sn,n)];r._c='gp';mr.push(r);for(const[b,o]of[...g.entries()].sort((x,y)=>y[1][0]-x[1][0])){const q=[b,fmt(o[0]),fmt(o[1]),pc(o[0],n)];q._c='sb';mr.push(q)}}
 mr.push(['TOTAL',fmt(n),fmt(be),'100.0%']);
 const gaps=yr(EALL).map(r=>[r[0],r[3],0]).filter(r=>r[1]).sort((a,b)=>b[1]-a[1]),
  top=[...I].sort((a,b)=>ebr(b)-ebr(a)||EC.ben[b]-EC.ben[a]).slice(0,25).map(i=>[EC.cm[i],EC.nom[i],EC.ut[i],EC.dis[i],fmt(EC.ben[i]),ebr(i)]);
 return`<div class=note>🍼 <b>EDUCUNAS 2026.</b> Fuente: EDUCUNAS_2026.xlsx (${fmt(ED.n)} SSEE del Servicio de Educación y Cuidado Diurno). Se aplican los filtros de <b>ubicación</b> (unidad territorial, departamento, provincia, distrito); los demás filtros no aplican porque EDUCUNAS trae su propia propuesta 2027. Las respuestas se normalizaron (Sí/No/No aplica/Sin dato). <b>Indicadores compuestos</b> (cocina adecuada, equipamiento completo, almacén adecuado, frío operativo, cocina integral) son construcciones del tablero con las variables del diccionario.</div>`
 +kpis([['SSEE EDUCUNAS',fmt(n),fmt(ED.n)+' en el archivo'],['Beneficiarios',fmt(be),'Prom. '+f1(be/n)+' por SSEE'],['Secciones',fmt(sec),f1(sec/n)+' por SSEE'],['Distritos',fmt(dis),fmt(um.size)+' unidades territoriales'],['Con comentarios',pc(I.filter(i=>EC.com[i]).length,n),fmt(I.filter(i=>EC.com[i]).length)+' SSEE']],'EDUCUNAS · indicadores generales')
 +kpis([['Cocina en condiciones adecuadas',pc(I.filter(kAd).length,n),'Ambiente + paredes, techo y piso adecuados'],['Equipamiento de cocina completo',pc(I.filter(kEq).length,n),'Artefacto, mesa, ollas y utensilios'],['Almacén adecuado',pc(I.filter(aAd).length,n),'Ambiente, equipamiento y estructura adecuada'],['Sistema de frío operativo',pc(I.filter(fOk).length,n),'Refrigeradora óptima o aceptable'],['Cocina integral',pc(I.filter(kIn).length,n),'Cocina adecuada + equipo + agua + electricidad']],'EDUCUNAS · indicadores compuestos')
 +`<div class=grid2>`+bars('SSEE, por modalidad propuesta 2027',cntE(I,i=>EC.mod[i]||'Sin dato'),n)+bars('SSEE, por n.º de secciones',cntE(I,i=>EC.sec[i]+' sección(es)').sort((a,b)=>a[0]<b[0]?-1:1),n)+`</div>`
 +plainT('Propuesta 2027 · modalidad y forma de atención',['Modalidad / forma de atención','SSEE','Beneficiarios','% SSEE'],mr,true)
 +`<div class=grid2>`+bars('SSEE, por comité propuesto 2027 (Top 10)',cntE(I,i=>EC.comite[i]||'Sin dato'),n,10)+bars('SSEE, por vía de acceso',cntE(I,i=>EC.via[i]),n)+`</div>`
 +plainT('Condiciones por unidad territorial',['Unidad territorial','SSEE','Beneficiarios','% con cocina','% cocina adecuada','% equipamiento completo','% almacén adecuado','% frío operativo','Brechas por SSEE (prom.)'],ur,true)
 +bars('Principales brechas · SSEE que NO cuentan con la condición',gaps,n,12)
 +ynT('Cocina · cumplimiento por condición',COC)+`<div class=grid2>`+stE('Paredes de la cocina',ESC[0])+stE('Techo de la cocina',ESC[1])+stE('Piso de la cocina',ESC[2])+bars('Combustible de cocina',cntE(I,i=>EC.comb[i]),n)+`</div>`
 +ynT('Almacén y sistema de frío · cumplimiento por condición',ALM)+`<div class=grid2>`+stE('Paredes del almacén',ESA[0])+stE('Techo del almacén',ESA[1])+stE('Piso del almacén',ESA[2])+bars('Tipo de almacenamiento',cntE(I,i=>EC.alm[i]),n)+`</div>`
 +`<div class=grid2>`+bars('Estado de la refrigeradora',cntE(I,i=>EC.ref[i]),n)+bars('Estado del microondas',cntE(I,i=>EC.mic[i]),n)+`</div>`
 +tbl('SSEE con mayor número de brechas (Top 25)',['Cód. modular','SSEE','Unidad territorial','Distrito','Beneficiarios','N.º de brechas'],top,null,25,{ns:1,c:'tx3'})
 +`<p class=meta>* % de cumplimiento = Sí / (Sí + No), excluyendo «No aplica» y «Sin dato». Brecha = respuesta «No» en cocina/almacén/frío, estado «Crítico» o equipo «Malo / inoperativo».</p>`};

/* ---------- render ---------- */
const filtros=()=>FIL.map(([c])=>Dd[c][sel[c]]?lb(Dd[c][sel[c]]):null).filter(Boolean).join(' · ');
function render(){R=[];const ixx=ix(0);$('#ttl').textContent=TT[tab];$('#out').innerHTML=(tab==='his'||tab==='edu')?T[tab]():T[tab](ixx);
 $('#meta').innerHTML=tab==='edu'?edMeta():`<b>${fmt(ixx.length)}</b> SSEE · <b>${fmt(ixx.reduce((a,i)=>a+U[i],0))}</b> usuarios · ${filtros()||'sin filtros'}`;
 if(tab==='grp'){drawMap();gfilter()}if(tab==='fic'){fres();let tq;$('#q').oninput=e=>{QS=e.target.value;clearTimeout(tq);tq=setTimeout(fres,200)}}}
const GRP=[['📅','Operatividad PAE',['periodo_sae','grupo_sae_educunas']],['📍','Ubicación',['unidad_territorial','departamento','provincia','distrito','area']],['🍽','Servicio',['nivel','modalidad','tipo_racion']]],FL=Object.fromEntries(FIL);let OP=-1;
function casc(c){if(c!=='provincia'&&c!=='distrito')return null;const s=new Set,D=C.departamento,P=C.provincia,X=C[c];for(let i=0;i<N;i++){if(sel.departamento>=0&&D[i]!==sel.departamento)continue;if(c==='distrito'&&sel.provincia>=0&&P[i]!==sel.provincia)continue;s.add(X[i])}return s}
function buildF(){$('#cmb').innerHTML=GRP.map(([ic,t,cs],g)=>`<div class=combo><button class="cb ${OP===g?'on':''}" data-p=${g}><span class=ci>${ic}</span><span class=ct><small>${t}</small><b>${cs.map(c=>sel[c]>=0?lb(Dd[c][sel[c]]):null).filter(Boolean).join(' · ')||(g===1?'Todo el país':'Todos')}</b></span><i>⌄</i></button><div class=pop ${OP===g?'':'hidden'}>${cs.map(c=>{const s=casc(c);return`<label>${FL[c]}<select data-c=${c}>${c==='periodo_sae'?'':'<option value=-1>Todos</option>'}${Dd[c].map((x,k)=>[x,k]).filter(([x,k])=>!s||s.has(k)).sort((a,b)=>a[0]<b[0]?-1:1).map(([x,k])=>`<option value=${k} ${sel[c]===k?'selected':''}>${lb(x)}</option>`).join('')}</select></label>`}).join('')}</div></div>`).join('')}
$('#filtros').onclick=e=>{const b=e.target.closest('.cb');if(b){const g=+b.dataset.p;OP=OP===g?-1:g;return buildF()}if(e.target.closest('#reset')){FIL.forEach(([c])=>sel[c]=-1);sel.periodo_sae=Dd.periodo_sae.indexOf('2027');OP=-1;buildF();render()}};
$('#filtros').onchange=e=>{const c=e.target.dataset.c;if(!c)return;sel[c]=+e.target.value;if(c==='departamento'){sel.provincia=-1;sel.distrito=-1}if(c==='provincia')sel.distrito=-1;buildF();render()};
document.addEventListener('click',e=>{if(!e.target.closest('.combo')&&OP>=0){OP=-1;buildF()}});
buildF();
$('#tabs').onclick=e=>{const b=e.target.closest('button');if(!b)return;$('#ficha').hidden=true;tab=b.dataset.t;document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('on',x===b));render();scrollTo(0,0)};
$('#theme').onclick=()=>{const d=document.documentElement;d.dataset.theme=(d.dataset.theme||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'))==='dark'?'light':'dark'};
$('#out').oninput=e=>{if(e.target.id==='gq'){G.q=e.target.value;gfilter()}if(e.target.id==='amt'){AMT=e.target.value;$('#ampv').innerHTML=amDoc(ix(0))}};
$('#out').onclick=e=>{const md=e.target.closest('[data-mod]');if(md){sel.modalidad=+md.dataset.mod;buildF();return render()}if(e.target.closest('#amdoc'))return amWord();const m=e.target.closest('[data-mat]');if(m){MAT=m.dataset.mat;return render()}const r=e.target.closest('tr[data-k]'),f=e.target.closest('tr[data-f]');
 if(f){ficha(+f.dataset.f);if(tab==='fic')focusF(+f.dataset.f);return}if(!r)return;const[t,k]=r.dataset.k.split(':');if(t==='ut'){sel.unidad_territorial=+k;document.querySelector('[data-c=unidad_territorial]').value=k;render()}else{G.sel=k;drawMap();$('#map').scrollIntoView({behavior:'smooth',block:'center'})}};
$('#out').onmouseover=e=>{const f=e.target.closest('tr[data-f]');if(f&&tab==='fic')focusF(+f.dataset.f,1)};
$('#out').onchange=e=>{if(e.target.id==='gby'){G.by=e.target.value;render()}if(e.target.id==='ggeo'){G.geo=e.target.value;render()}};
/* ---------- reportes ---------- */
var CSS='body{font-family:Calibri,Arial,sans-serif;color:#0f172a}h1{color:#0b1f47}h2{color:#1d4ed8;border-bottom:2px solid #f59e0b;font-size:13pt}table{border-collapse:collapse}th,td{border:1px solid #94a3b8;padding:3px 7px;font-size:10pt}th{background:#dbe8f7}';

var dl=(txt,name,type)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type}));a.download=name;a.click()};
document.querySelector('.hr').onclick=e=>{const x=e.target.dataset.x;if(!x)return;if(x==='doc'&&tab==='am')return amWord();const nm='SAE_'+tab+'_'+(Dd.periodo_sae[sel.periodo_sae]||'');
 if(x==='pdf')print();if(x==='doc')dl('\ufeff'+rep(1),nm+'.doc','application/msword');if(x==='xls')dl('\ufeff'+rep(),nm+'.xls','application/vnd.ms-excel');
 if(x==='csv'){if(tab==='edu')return edCsv();const cs=Object.keys(C),q=s=>'"'+String(s).replace(/"/g,'""')+'"',L=['periodo_sae,'+cs.filter(c=>c!=='periodo_sae').concat(['usuarios','latitud','longitud']).join(',')];for(const i of ix(0))L.push(q(v('periodo_sae',i))+','+cs.filter(c=>c!=='periodo_sae').map(c=>q(v(c,i))).concat([U[i],LA[i],LO[i]]).join(','));dl('\ufeff'+L.join('\n'),'SAE_base_filtrada.csv','text/csv')}};
render();
